Add Team Member Management Commands
CrunchyData/bridge-cli pull request #21
Opened 2022-04-12 14:39 UTC by abrightwell

Add support for `team-member` management.

Adds command support for `team-member` management.

Implements:

`add` - add member to a team.
`info` - show details of a team member.
`list` - list current members of a team.
`update` - updates member of team - currently only supports updating role.
`remove` - removes member from team.

```
> cb team-member --help
Usage:
    cb team-member <command>

Available Commands:
    add                              Add a team member
    info                             Show team member details
    list                             List members of a team
    remove                           Remove a member from a team
    update                           Update a member of a team

Options:
    -h, --help                       Show this help
```

2022-04-12 16:13 UTC, brandur reviewed
Seems good to me, but like last one will leave full review to Will.

2022-04-12 16:13 UTC, brandur commented on spec/cb/team_member_spec.cr
> +  it "#run" do
May be a pre-existing problem, but generally these spec names are called `it` so that they read as a sentence like "it succeeds" or "it validates that required arguments are present". For method names, you'd normally put those in a `describe` block with an `it` test case wrapped below. Not a big deal though.

2022-04-12 16:13 UTC, brandur commented on src/cb/completion.cr
> +    suggest << "--account\tuser's account ID" unless has_full_flag?(:account) || has_full_flag?(:email)
Another pre-existing one, but most Rubyists (I thinkk I'm fair in saying that) consider it bad practice to use complex `unless` cases because they're really hard to mentally parse.

My last job banned `unless` that had more one condition via Rubocop.

This one isn't too bad, but worth thinking about.

2022-04-14 17:43 UTC, will commented on spec/cb/team_member_spec.cr
> +  it "#run" do
Part of it I think is per-test setup is a little more cumbersome in the stdlib crystal test than ruby's 3rd party rspec, so you end up making more combined test that have more than one assertion. 

However I recently came across https://gitlab.com/arctic-fox/spectator/-/wikis/Mocks-and-Doubles which looks pretty neat, and might be worth switching to.

2022-04-14 18:02 UTC, will commented on src/cb/client.cr
> +    end
```suggestion
    def to_s(io : IO)
      io << id.colorize.t_id << " (" << name.colorize.t_name << ")"
    end
```

https://crystal-lang.org/reference/1.4/guides/performance.html#dont-create-intermediate-strings-when-writing-to-an-io explains why better than I could

2022-04-14 18:46 UTC, will commented on src/cb/completion.cr
> +    suggest << "--account\tuser's account ID" unless has_full_flag?(:account) || has_full_flag?(:email)
I agree with all of this. In general once a conditional gets any more complicated than a single thing, you should avoid `unless`.

However for this particular set of lines `unless` is very good. "Add this option unless we have that flag" just is really great. And going to "add this option unless there is that flag or that other flag" isn't too much of a stretch to that.

Also switching it to an `if` in this case I think makes it worse than the `unless` (which is often not the case)

```crystal
suggest << "--account\tuser's account ID" if !(has_full_flag?(:account) || has_full_flag?(:email))
# or
suggest << "--account\tuser's account ID" if !has_full_flag?(:account) && !has_full_flag?(:email)
 ```

So for this particular instance keeping the `unless` is the best thing I think. But for sure it's a keyword to pay attention to abusing.

2022-04-14 18:53 UTC, abrightwell commented on src/cb/client.cr
> +    end
Ah! Very cool. I didn't realize that's how it was handling things under the hood, but it makes perfect sense. :+1:

2022-04-14 18:56 UTC, will commented on src/cb/completion.cr
> +    suggest << "--account\tuser's account ID" unless has_full_flag?(:account) || has_full_flag?(:email)
`has_full_flag?` can take multiple flags, but it wants *all* flags to be there for it to be true.

We could maybe make a method 

```crystal
def has_any_full_flag?(*names : Symbol)
   names.any? { |n| @full_flags.includes? n }
end

# then it could be
<< "thing" unless has_any_full_flag? :a, :b

```

Which might be a bit easier to reason about? Not fully sure either way.

2022-04-14 19:37 UTC, will requested changes
Just really the to_s thing, then if you want to explore the .any? option of the full_flag thing, but just if that feels nicer

2022-04-14 19:37 UTC, will commented on src/cb/team_member.cr
> +    # raise Error.new "Unknown team member '#{email.colorize.t_name}'"
Was this just something you were experimenting with? Should we have it in for real?

2022-04-18 15:47 UTC, abrightwell commented on src/cb/team_member.cr
> +    # raise Error.new "Unknown team member '#{email.colorize.t_name}'"
Yeah, meant to remove it... removed now though. :+1:

2022-04-19 00:56 UTC, merged