Add `--database` flag to `scope` and `psql`
CrunchyData/bridge-cli pull request #5
Opened 2022-01-18 20:45 UTC by abrightwell

These changes add the ability to specify a database name to connect when
using the `scope` and `psql` command.

The flag is setup to be optional. If not provided then it will default
to `postgres`.

Example with `psql`:

```
> ./bin/cb psql <test-cluster-id>
connecting to personal/test-cluster
psql (14.1 (Ubuntu 14.1-1.pgdg18.04+1), server 13.4)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

personal/test-cluster/postgres=# \q

> ./bin/cb psql <test-cluster-id> --database foo
connecting to personal/test-cluster
psql (14.1 (Ubuntu 14.1-1.pgdg18.04+1), server 13.4)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

personal/test-cluster/foo=# \q
```

2022-01-18 20:46 UTC, abrightwell commented on spec/cb/completion_spec.cr
> -    result.should eq ([] of String)
The changes in this file were just from running `crystal tool format`.

2022-01-18 20:46 UTC, abrightwell commented on src/cb/psql.cr
> +      "PGDATABASE"    => database.nil? ? uri.path.lchop('/') : database,
Not sure if this is desirable or doing like was done in `scope` and just reassigning `uri.path` if the flag was set.

2022-01-24 14:00 UTC, will commented on spec/cb/completion_spec.cr
> -    result.should eq ([] of String)
I moved this to it's own commit since I merged some of the other things first, so we can remove these changes from this PR

2022-01-24 15:19 UTC, will requested changes
Could you please also add completion and completion specs, and a changelog entry?

2022-01-24 15:19 UTC, will commented on src/cb/psql.cr
> +    str = str.downcase
Do we want this? I don’t know what happens if people have upper case characters in their database name with postgres at all.

2022-01-24 15:19 UTC, will commented on src/cli.cr
> +    parser.banner = "Usage: cb psql <cluster id> [<--database>] [-- [args for psql such as -c or -f]]"
```suggestion
    parser.banner = "Usage: cb psql <cluster id> [--database] [-- [args for psql such as -c or -f]]"
```

I've been going with `[]` is for optional and `<>` for required, so I think we just need the `[]`

2022-01-24 15:19 UTC, will commented on src/cb/psql.cr
> +    end
This is the same reason as the case in the other PR with the instance variable still being a union with nil even in the conditional. It is technically possible for some thread to change the value of `@database` (which these two call to `#database` is returning) to change between calls. For this cli program, it'll never happen, but that's why the call to `#presence` really isn't doing much, and why I think probably the complier made you tack on `#to_s`.



One way would be 
```suggestion
    if (db = database)
      uri.path = db
    end
```

But also you could do it I think like this, which is nice because the above creates a local variable that is in scope for the rest of the method, whereas the block argument is only in scope in the block.

```suggestion
    database.tap { |db| uri.path = db if db }
```

I don’t think it matters a whole lot either way. Just explaining all the options and what's going on assuming you're new to Crystal.

2022-01-25 16:43 UTC, abrightwell commented on src/cb/psql.cr
> +    str = str.downcase
So, yeah, it's likely not necessary, but testing `foo` vs `FOO` it does the right thing. So really should matter, will remove.

2022-01-27 15:29 UTC, merged