Add maintenance on info
CrunchyData/bridge-cli pull request #75
Opened 2022-11-03 17:12 UTC by ngaumont

They are quite a lot of information for this option, but I tried to give the more inputs to the end user.

2022-11-08 21:13 UTC, abrightwell requested changes
A couple comments and suggestions.

Also, I'm curious if it would make sense to perhaps break out `MaintenanceWindow` into it's own class. That way the `action` is purely an action/command.

2022-11-08 21:13 UTC, abrightwell commented on spec/cb/cluster_info_spec.cr
> +        maintenance: no window set. Operations such as disk scaling, resize and postgres upgrade happens as soon as possible.
I'm curious if this should be `maintenance window` instead of just `maintenance`. I don't have a strong opinion here, my only thought is that perhaps it should be more explicit to avoid potential confusion.

2022-11-08 21:13 UTC, abrightwell commented on src/cli.cr
> +      parser.banner = "cb maintenance update <--cluster>"
If `--window-start` is required then let's list it in the banner.

```suggestion
      parser.banner = "cb maintenance update <--cluster> <--window-start>"
```

2022-11-08 21:13 UTC, abrightwell commented on src/cli.cr
> +      parser.on("--window-start START", "Hour maintenance window start (UTC). -1 to unset") { |arg| update.window_start = arg }
I know that the API uses `-1` to reset. But I'm curious if we could perhaps create a better experience for the user. For instance. Perhaps instead we either 1) offer another option called `--unset` or maybe we provide an enum of valid values for `--window-start` where something like `NONE` or similar would be translated to -1. :thinking:  It also might be a good idea to do some checks to ensure valid input for this option as well, None,0-23... or whatever.

2022-11-09 10:45 UTC, ngaumont commented on src/cb/maintenance.cr
> +  def self.window_start_explanation(maintenance_start : Int32?, now : Time? = nil)
This can't be an instance method, as it's also called in `cluster_info.cr`.
I did not find any better solution than class method …

2022-11-09 10:49 UTC, ngaumont commented on src/cb/maintenance.cr
> +      return "no window set. Operations such as disk scaling, resize and postgres upgrade happens as soon as possible."
Maybe no so verbose, but like this ?

```
no window set. Operations happens as soon as possible
```
I fear that the user might think that nothing will happen to his cluster because there is no window.
If I'm the only one with the fear, I'm good with only no window set.

2022-11-09 10:50 UTC, ngaumont commented on spec/cb/cluster_info_spec.cr
> +        maintenance: no window set. Operations such as disk scaling, resize and postgres upgrade happens as soon as possible.
I first used `maintenance window`, but this ended being very long with the description I had. With a shorter description, it fit.

2022-11-09 13:25 UTC, will commented on src/cb/maintenance.cr
> +      return "no window set. Operations such as disk scaling, resize and postgres upgrade happens as soon as possible."
Maybe show `00:00-23:59` or something similar to indicate it's the entire day when there is no window set?

2022-11-09 16:19 UTC, abrightwell requested changes
One minor adjustment. Otherwise, LGTM.

2022-11-09 16:19 UTC, abrightwell commented on src/cb/maintenance.cr
> +    raise Error.new "window-start should be between 0 and 23" if (start = window_start) && (start < 0 || start > 23)
```suggestion
    raise Error.new "Must use '--window-start' or '--unset' but not both." if window_start && unset
    raise Error.new "'--window-start' should be between 0 and 23" if (start = window_start) && (start < 0 || start > 23)
```

2022-11-09 16:25 UTC, ngaumont commented
> Also, I'm curious if it would make sense to perhaps break out `MaintenanceWindow` into it's own class. That way the `action` is purely an action/command.

I create a fixup and let you decide what you prefer

2022-11-09 17:45 UTC, abrightwell approved these changes

2022-11-10 10:18 UTC, merged