Add `--version` flag to `create` command.
CrunchyData/bridge-cli pull request #8
Opened 2022-01-20 14:34 UTC by abrightwell

This flag allows for specifying the postgres major version to the create
command. It is currently set to default to version 13.

2022-01-24 15:03 UTC, will requested changes
There isn't tab completion for the flag. It's a bit of a daunting section through, so I did this one as an example https://github.com/CrunchyData/bridge-cli/commit/cafe18a723a7f3e0758e3d635082699e87010a7e 

I think you can't pick a different version for a replica so I've excluded the suggestion if the replica field was set. 

Could you also please add a changelog?

2022-01-25 17:12 UTC, abrightwell commented on src/cb/cluster_create.cr
> +      self.postgres_version ||= 13
The API does not default to any version, unfortunately. There was a deprecation of `major_version` in favor of `postgres_version_id`. For backwards compat, if the latter was omitted, it would default to the former. Current version of the CLI assigns statically to 13. Though, that's not an argument not to default in the API, which seems like a reasonable improvement to introduce. @brandur thoughts on setting a default major version?

2022-01-25 17:24 UTC, brandur commented on src/cb/cluster_create.cr
> +      self.postgres_version ||= 13
WFM.

We already do kind of have a default in that there's one in there for Heroku in case someone doesn't passes any flags to `heroku addons:add`. We may want to expand on this and make this a global thing which would allow you to not pass any `postgres_version_id` to "cluster create", making it a bit easier to call.

2022-01-25 19:25 UTC, brandur commented on src/cli.cr
> +    parser.on("-v VERSION", "--version VERSION", "Postgres version (default: 13)") { |arg| create.postgres_version = arg }
+1.

2022-01-25 19:26 UTC, brandur commented on src/cb/cluster_create.cr
> +      self.postgres_version ||= 13
Put up: https://github.com/CrunchyData/priv-all-crunchy-cloud-manager/pull/1500

I'll bump the default to 14 as well.

2022-01-25 19:42 UTC, abrightwell commented on src/cb/completion.cr
> +    suggest << "--version\tmajor version" unless has_full_flag?(:version) || has_full_flag?(:fork) || has_full_flag?(:replica)
I double checked, neither fork nor replica allow for a version to be specified.

2022-01-25 21:00 UTC, brandur commented on src/cb/cluster_create.cr
> +      self.postgres_version ||= 13
This change is deployed and Postgres 14 is now the Platform-wide default.

2022-01-27 15:52 UTC, will commented
This is merged but I did the rebase on my computer so gh didn't figure it out

2022-01-27 15:52 UTC, closed without merging