Schedule maintenance
CrunchyData/bridge-cli pull request #81
Opened 2022-12-01 17:06 UTC by ngaumont

2022-12-01 18:54 UTC, abrightwell requested changes

2022-12-01 18:54 UTC, abrightwell commented on spec/cb/maintenance_spec.cr
> +  it "reject if both now and starting-from are present" do
```suggestion
  it "rejects if both now and starting-from are present" do
```

2022-12-01 18:54 UTC, abrightwell commented on spec/cb/maintenance_spec.cr
> +  it "reject invalid window-start " do
```suggestion
  it "rejects invalid window-start " do
```

2022-12-01 18:54 UTC, abrightwell commented on src/cb/action.cr
> +        raise_arg_error "#{{{property.stringify}}} in rfc3339 like #{Time.local.to_rfc3339}", str
I think it would be best to establish a 'time' example, instead of having it be variable with each error.

```suggestion
        raise_arg_error "#{{{property.stringify}}} must be in rfc3339 format, e.g. 2022-01-01T00:00:00Z", str
```

2022-12-01 18:54 UTC, abrightwell commented on src/cb/completion.cr
> +    suggest << "--starting-from\tSchedule a maintenance in RFC3339" unless has_full_flag?(:now) || has_full_flag?(:starting_from)
```suggestion
    suggest << "--starting-from\tStarting time to schedule a maintenance. (RFC3339 format)" unless has_full_flag?(:now) || has_full_flag?(:starting_from)
```

2022-12-02 13:59 UTC, abrightwell approved these changes

2022-12-02 17:07 UTC, ngaumont commented
This depends on: https://github.com/CrunchyData/priv-all-cloud-owl/pull/1792

2022-12-15 14:35 UTC, abrightwell commented on spec/cb/maintenance_spec.cr
> +
Can we add a describe here to group the different function calls?

For instance:

```
describe "#validate" do
  it "rejects invalid starting-from" do
  ...
  end
end  
```

And the same for `#run` below?

`spec/cb/config_param_spec.cr` in #83 would be a good example for this, I think.

2022-12-15 16:54 UTC, ngaumont commented
This is now a breaking PR that will need a version bump as a command is changed (`maintenance update` updated to `maintenance set`)

2023-01-20 12:57 UTC, ngaumont commented
@abrightwell I updated this to follow the change the change from the api to the `upgrade` endpoint.
Another PR will add the update capability (both upgrade and maintenance)

2023-01-25 22:11 UTC, abrightwell requested changes

2023-01-25 22:11 UTC, abrightwell commented on spec/cb/cluster_upgrade_spec.cr
> +  subject(action) { described_class.new client: client, output: IO::Memory.new }
Just reorder this here... I'm trying to keep to the convention of defining the `subject` as the first line.
```suggestion
  subject(action) { described_class.new client: client, output: IO::Memory.new }

  let(cluster) { Factory.cluster }
```

2023-01-25 22:11 UTC, abrightwell commented on src/cb/completion.cr
> +        "info\tdisplay cluster maintenance window and pending maintenance",
I think keeping this as it was is fine. That way if we want to add some more information later, it's generic enough to cover that case.

```suggestion
        "info\tdisplay cluster maintenance information",
```

2023-01-25 22:11 UTC, abrightwell commented on src/cli.cr
> +        Upgrade to add an ha
```suggestion
        Upgrade to high availability.
```

2023-01-25 22:11 UTC, abrightwell commented on src/cli.cr
> +        Upgrade storage to 200 GiB without that will failover during the cluster maintenance window
```suggestion
        Upgrade storage and failover during the cluster maintenance window.
```

2023-01-25 22:11 UTC, abrightwell commented on src/cli.cr
> +        Upgrade plan to 'memory-128' that will failover as soon as possible
```suggestion
        Upgrade plan and failover as soon as possible.
```

2023-01-25 22:11 UTC, abrightwell commented on src/cli.cr
> +        Upgrade both postgre major version and storage that will failover starting from a given time
```suggestion
        Upgrade postgres major version and storage and failover at the given time.
```

2023-01-25 22:11 UTC, abrightwell commented on CHANGELOG.md
> +   specify upgrade failower window. Default to cluster maintenance window.
```suggestion
- `cb upgrade start` command accepts `--starting-from` and `--now` options that
   specify upgrade failover window.
```

2023-01-26 09:19 UTC, ngaumont commented on src/cb/completion.cr
> +        "info\tdisplay cluster maintenance window and pending maintenance",
I also updated the same text in `cli.cr`

2023-01-26 13:52 UTC, abrightwell approved these changes
:+1:

2023-01-26 13:58 UTC, merged